version: "3"

services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      #- UMASK_SET=022 #optional
    volumes:
      - ./volumes/plex/config:/config
      - /media/nas/Series:/tv
      - /media/nas/Films:/movies
      - ./volumes/plex/transcode:/transcode
    restart: unless-stopped
