---
location_base: "~/services"
location_systemd: "/etc/systemd/system"

location_unit: "{{ location_systemd }}/{{ unit_file }}"
location_service: "{{ location_base }}/plex-server"
location_docker_compose_config: "{{ location_service }}/docker-compose.yml"

unit_name: plex
unit_file: "{{ unit_name }}.service"

media:
  local_path: /media/nas
  remote_path: /Multimedia/Video
