---
- name: create folder
  become: no
  file:
    path: "{{ location_base }}"
    state: directory

- name: Copy docker-compose.yml
  become: no
  copy:
    src: docker-compose.yml
    dest: "{{ location_docker_compose_config }}"

- name: Copy plex.service
  template:
    src: "{{ unit_file }}"
    dest: "{{ location_unit }}"

- name: Reload systemd config
  service:
    daemon_reload: yes

- name: Enable & restart service
  service:
    name: "{{ unit_name }}"
    state: restarted
    enabled: yes

- name: Open port 32400 for TCP traffic
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 32400
    jump: ACCEPT
  notify:
    - Save iptables
